### ISSUE TITLE
How to use “sfdx force:source:pull” when folders other than “main/default” are used and components are added in the scratch org?

### ISSUE THREAD

**Issue by KeithClarke** [sfdx-isv/sfdx-falcon-template#2]
I've setup the folder structure for a new project following the patterns identified here. When I add e.g. a new SObject in the scratch org and use:

`sfdx force:source:pull`

the new components are put in a fixed folder "main/default" - there is no option to nominate the correct folder. So the folder structure is compromised.

(When components are already present locally in folders other than "main/default" the pull does place the changes correctly.)

Is there a work-around for this problem? If there isn't this multiple folder approach needs revising. So far I've wasted several hours trying to find a work around.

(Same question posted here https://salesforce.stackexchange.com/questions/206847/how-to-use-sfdx-forcesourcepull-when-folders-other-than-main-default-are-u.)

**Comment by tmowbrey** [comment]
I believe this is the way the system is designed. All new changes made in the Salesforce org are put in the "default" folder when using sfdx force:source:pull. This ensures that the CLI always knows where changes go that you have not yet allocated to a different part of your folder structure.

Once you move the file to another part of the folder structure, the CLI retains that information and then is able to maintain that change going forward.

This makes perfect sense to me, until I tell a file where to go, the system doesn't know, hence I have a default place for files the system doesn't know what to do with.

**Comment by loganm** [comment]
I've been wondering about adding the `main/default` source folder to the `.gitignore` file. This would force contributors to move the newly added source folders to an appropriate directory. I worry that the default folder will become a dumping ground for all source files.
