### ISSUE TITLE
Custom Metadata "records" not being synced

### ISSUE THREAD

**Issue by DougYounger** [sfdx-isv/sfdx-falcon-template#6]
It seems like the **.md entry in .forceignore is interfering with processing the custom metadata records.
The file extension for the MDAPI files is .md, and the DX files are .md-meta.xml
I changed the entry to: *README.md to ignore the readme files and was able to pull/push/convert them.

**Comment by newspore** [comment]
I also did found on this that if you want to deploy the Records. 
using SFDX force:source:deploy -x "manifest/package.xml" you will need to use a WildCard in the Members of the CustomMetadata, individual Records are just returning that the "File was not found" even if I used the same package to retrieve it.
