### ISSUE TITLE
How to keep template users upgradable?

### ISSUE THREAD

**Issue by rsoesemann** [sfdx-isv/sfdx-falcon-template#9]
We took the Falcon template and adjusted it for ou purposes:

1. Corrected errors
2. Added CircleCI workflow steps
3. Created Powershell version of the scripts
4. Fixed bugs

What happens now when the repo is updated by Salesforce? The simple answer is we have to manually find and merge any change. Sure. But isn't there a better way to keep consumers of the template upgradable?

An idea could be to minimize the script parts to a minimum and provide a SFDX Falcon Plugin which only needs a ISV package specific configuration.

**Comment by VivekMChawla** [comment]
@rsoesemann - I'm with you 100%.  That's exactly what I'm working on with the SFDX-Falcon plugin right now.  I started with the "ADK" (AppExchange *Demo* Kit) feature of the plugin, but will soon be moving onto the "APK" (AppExchange *Package* Kit) part.

Beyond that, I think it's also worth the time for me to take a closer look at what a template upgrade path would look like.  I'd like to work with you to learn the way's that you've customized Falcon and then work backwards from there to see how I could generalize things better to make updates to the "core" project easier to push out to any forks.

**Comment by rsoesemann** [comment]
Sure. More than happy to help. In case you want to have a look at how we use it, here is the publich Github repo https://github.com/Up2Go/travelexpenses
